import dustbin from "@/assets/issue-dustbin.jpg";
import pigeon from "@/assets/issue-pigeon.jpg";
import plastic from "@/assets/issue-plastic.jpg";
import food from "@/assets/issue-food.jpg";
import type { Report } from "./types";

export const DEMO_IMAGES = { dustbin, pigeon, plastic, food };

const day = 86_400_000;
const ago = (days: number, hour = 10) => {
  const d = new Date(Date.now() - days * day);
  d.setHours(hour, (days * 17) % 60, 0, 0);
  return d.toISOString();
};

export const demoReports: Report[] = [
  {
    id: "CH-1041",
    student: "Aarav Sharma",
    block: "Block B",
    location: "Corridor",
    description: "Dustbin near room 112 has not been emptied for two days.",
    photo: dustbin,
    analysis: {
      problem: "Overflowing dustbin with mixed waste spilling onto the floor",
      wasteType: "Overflowing Dustbin",
      severity: "High",
      recommendation: "Empty the bin immediately and sanitise the surrounding floor area.",
      confidence: 0.94,
    },
    createdAt: ago(0, 9),
    status: "Cleaning in Progress",
    assignedTo: "Ramesh K.",
  },
  {
    id: "CH-1040",
    student: "Priya Nair",
    block: "Block A",
    location: "Window Ledge",
    description: "Pigeons sitting on my window ledge every morning.",
    photo: pigeon,
    analysis: {
      problem: "Pigeon waste detected near hostel window ledge",
      wasteType: "Pigeon / Bird Waste",
      severity: "High",
      recommendation: "Disinfect the ledge with bleach solution and install bird netting.",
      confidence: 0.91,
    },
    createdAt: ago(1, 8),
    status: "Assigned",
    assignedTo: "Suman Devi",
  },
  {
    id: "CH-1039",
    student: "Rohit Verma",
    block: "Block C",
    location: "Staircase",
    description: "Plastic bottles and wrappers thrown near the staircase.",
    photo: plastic,
    analysis: {
      problem: "Scattered plastic bottles and snack wrappers on the ground",
      wasteType: "Plastic Waste",
      severity: "Medium",
      recommendation: "Collect and segregate plastic for recycling; place a bin at the stairs.",
      confidence: 0.88,
    },
    createdAt: ago(1, 17),
    status: "Reported",
  },
  {
    id: "CH-1038",
    student: "Sneha Iyer",
    block: "Girls Hostel",
    location: "Canteen / Mess",
    description: "Plates with leftover food left on the counter after dinner.",
    photo: food,
    analysis: {
      problem: "Leftover food waste and unwashed plates near canteen counter",
      wasteType: "Food Waste",
      severity: "Medium",
      recommendation: "Clear plates, wipe the counter and schedule a post-dinner cleaning round.",
      confidence: 0.86,
    },
    createdAt: ago(2, 21),
    status: "Resolved",
    assignedTo: "Lakshmi N.",
    resolvedAt: ago(2, 23),
  },
  {
    id: "CH-1037",
    student: "Aarav Sharma",
    block: "Block B",
    location: "Washroom",
    description: "Floor is wet and dirty near the washbasins.",
    photo: dustbin,
    analysis: {
      problem: "Dirty and wet floor with visible stains",
      wasteType: "Dirty Floor",
      severity: "Medium",
      recommendation: "Mop with disinfectant and check for drainage blockage.",
      confidence: 0.82,
    },
    createdAt: ago(3, 11),
    status: "Resolved",
    assignedTo: "Arjun P.",
    resolvedAt: ago(3, 15),
  },
  {
    id: "CH-1036",
    student: "Kabir Malhotra",
    block: "Block D",
    location: "Parking / Entrance",
    description: "Garbage bags dumped at the entrance gate.",
    photo: plastic,
    analysis: {
      problem: "Garbage bags dumped outside the designated collection point",
      wasteType: "Garbage / Mixed Waste",
      severity: "High",
      recommendation: "Move waste to the collection point and schedule daily pickup.",
      confidence: 0.9,
    },
    createdAt: ago(4, 7),
    status: "Resolved",
    assignedTo: "Vikram S.",
    resolvedAt: ago(4, 12),
  },
  {
    id: "CH-1035",
    student: "Priya Nair",
    block: "Block A",
    location: "Common Room",
    description: "Snack packets left on the sofa after movie night.",
    photo: plastic,
    analysis: {
      problem: "Scattered snack packets and cups in the common room",
      wasteType: "Plastic Waste",
      severity: "Low",
      recommendation: "Quick sweep and add a labelled dry-waste bin in the room.",
      confidence: 0.79,
    },
    createdAt: ago(5, 20),
    status: "Resolved",
    assignedTo: "Ramesh K.",
    resolvedAt: ago(5, 22),
  },
  {
    id: "CH-1034",
    student: "Sneha Iyer",
    block: "Girls Hostel",
    location: "Corridor",
    description: "Dust and wrappers along the first floor corridor.",
    photo: dustbin,
    analysis: {
      problem: "Dirty corridor with dust accumulation and litter",
      wasteType: "Dirty Floor",
      severity: "Low",
      recommendation: "Routine sweeping and mopping of the corridor.",
      confidence: 0.77,
    },
    createdAt: ago(6, 13),
    status: "Resolved",
    assignedTo: "Lakshmi N.",
    resolvedAt: ago(6, 16),
  },
  {
    id: "CH-1033",
    student: "Rohit Verma",
    block: "Block C",
    location: "Canteen / Mess",
    description: "Food waste near the washing area attracting flies.",
    photo: food,
    analysis: {
      problem: "Food waste accumulation attracting flies near the mess washing area",
      wasteType: "Food Waste",
      severity: "High",
      recommendation: "Clear waste into a covered wet-waste bin and spray disinfectant.",
      confidence: 0.92,
    },
    createdAt: ago(6, 9),
    status: "Resolved",
    assignedTo: "Arjun P.",
    resolvedAt: ago(6, 18),
  },
];
